### PR TITLE
Javadoc travis

### PR DESCRIPTION
**Pull request by jburel**
Run javadoc in travis
Check that travis is green

### CODE REVIEW

**Comment by joshmoore** [comment]
@jburel : if you plan to go back through all the travis files, does adding `-i` (or some form of verbosity) make sense so that we can see what tests were run? (a la https://github.com/ome/omero-java-gateway/pull/1#pullrequestreview-221088392)

**Comment by jburel** [comment]
We discussed that with @dominikl last week I am a bit worried that it is too verbose

**Comment by joshmoore** [comment]
Yeah, I know the feeling. An alternative might be to update one of the plugins to print a single line per test.

**Comment by jburel** [comment]
This will require a bit of investigation. Something for another round of work

**Comment by jburel** [comment]
issue created in that repo (it will apply to other repo) cf. test output
https://github.com/ome/omero-common/issues/16

**Pull request merged**
