### PR TITLE
Remove Guava dependency and improve error for large planes.

### PR DESCRIPTION
**Pull request by mtbc**
See exception at https://trello.com/c/a40Eyenx/607-renderingbean-arithmeticexception.

### CODE REVIEW

**Comment by rgozim** [comment]
Didn't this PR have an ordered delete function before 🤔?

**Comment by mtbc** [comment]
Are you thinking of https://github.com/ome/omero-server/pull/14?

**Comment by rgozim** [comment]
Just curious, is the `ArithmeticException` not enough in terms of error reporting for this instance? I would have imagined that `ArithmeticException` is more precise than an IllegalArgumentException. If you were to throw `IllegalArgumentException` I would put if statements right at the start of the method and explicitly compare to int max.

**Comment by mtbc** [comment]
If `Math.multiplyExact` already implements the check then I figure those implementors are highly likely to get the check correct and I may as well reuse their work; it's still just about one of the first things the method does. The existing `ArithmeticException` hardly tells us anything in the log and knowing what plane size was actually requested could be quite handy for debugging.

**Comment by mtbc** [comment]
(The current exception hardly gives the developer much of a hint that the problem was the plane size at all without making them dig into the server source!)

**Comment by joshmoore** [comment]
> is the ArithmeticException not enough in terms of error reporting for this instance?

We don't provide any ice mapping for `ArithmeticException`:

 * https://github.com/ome/omero-server/blob/master/src/main/java/ome/services/util/ServiceHandler.java#L181
 * https://github.com/ome/omero-blitz/blob/master/src/main/java/omero/util/IceMapper.java#L1340

**Comment by rgozim** [comment]
Good point Josh! Looking at the source for `multiplyExact` it looks like the `ArithmeticException` is thrown if the result of the actual multiply exceeds int max, and not the inputs. In any case it might be helpful to mention that in the re-thrown error message, something like "multiply result exceeds int max"

**Comment by joshmoore** [comment]
@mtbc : when was `IntMath` use added? (Hoping you know off-hand since that is now lost behind the git rename...otherwise, I'll dig it out) I was just comparing 

 * https://github.com/google/guava/blob/master/guava/src/com/google/common/math/IntMath.java#L476
 * https://github.com/google/guava/blob/master/guava/src/com/google/common/math/MathPreconditions.java#L95

so this would be a change of behavior, even if an improvement.

**Comment by mtbc** [comment]
It was introduced in 5.1.4.

**Comment by joshmoore** [comment]
:+1: I'll leave it to you to keep an eye on any change of behavior stemming from a different exception, but this bodes well:

```
/opt/omero-build $git submodule foreach -q 'git grep ArithmeticException || echo not in $name'
not in omero-blitz
not in omero-common
not in omero-model
not in omero-renderer
not in omero-romio
not in omero-server
```

**Pull request merged**
